// All user-facing wording lives here, so tone can be reviewed in one place.
// Tone: plain, warm, Socratic. Never tell the user they're wrong.
import type { Evidence } from '../model/content.ts';

export const copy = {
  appName: 'Who Am I',
  tagline: 'Find out where you stand, and why.',
  privacy: 'Everything stays on this device. No account, no tracking.',

  nav: { home: 'Home', topics: 'Topics', results: 'Results', settings: 'Settings' },

  home: {
    howTitle: 'How it works',
    how: [
      'Answer questions on the topics you choose. Skip anything.',
      "Face the strongest case against whatever you said. Hold your ground or reconsider.",
      'See where you stand, and where your answers pull in different directions.',
    ],
    startPersonality: 'Start with your personality',
    startPersonalityNote: 'About 2 minutes',
    browse: 'Browse topics',
    continueTitle: 'Pick up where you left off',
    continueTopic: (title: string, left: number) => `${title} · ${left} left`,
    nextTitle: 'Up next',
    progress: (done: number, total: number) => `${done} of ${total} topics finished`,
    seeResults: 'See your results',
    allDone: "You've finished every topic so far. More are on the way.",
  },

  topics: {
    title: 'Topics',
    intro: 'Pick any topic, in any order. Every question can be skipped.',
    start: 'Start',
    left: (n: number) => `${n} left`,
    done: 'Done',
    sensitive: 'Sensitive: never shared unless you choose to',
    deepDives: 'Deep dives',
    comingSoon: 'Coming soon',
    comingSoonNote: 'These areas are planned and will be added over time.',
  },

  flow: {
    exit: 'Close',
    back: 'Back',
    next: 'Next',
    skip: 'Skip',
    unsure: 'No opinion / not sure',
    declined: 'Prefer not to say',
    start: 'Start',
    noneOfThese: 'None of these',
    rateEach: 'How much do you like each?',
    slightly: 'Slightly',
    strongly: 'Strongly',
    noteToggle: 'Add a note (optional)',
    notePlaceholder: 'Why? Only you will see this.',
    challengeLabel: 'A challenge',
    reaskAfterChallenge: 'Having thought about that, where do you land now?',
    before: 'Before:',
    keep: 'Keep my answer',
    editing: 'Change your answer',
    cancelEdit: 'Cancel',
    sourceLabel: 'Source',
    progress: (answered: number, total: number) => `${answered} of about ${total}`,
    doneTitle: (topic: string) => `You've finished ${topic}`,
    landed: 'Where you landed',
    startedAt: (label: string) => `You started at “${label}”.`,
    moved: (steps: number, source: string) =>
      `“${source}” moved you ${Math.abs(steps)} step${Math.abs(steps) === 1 ? '' : 's'}.`,
    heldAll: (n: number) => (n === 1 ? 'You held your view through the challenge.' : `You held your view through all ${n} challenges.`),
    nextTopic: (title: string) => `Next: ${title}`,
    seeResults: 'See your results',
    reviewAnswers: 'Review your answers',
    backToTopics: 'All topics',
    notFound: "That topic doesn't exist (yet).",
  },

  tension: {
    title: 'Two of your answers pull in different directions',
    intro: (principle: string) => `Both are about ${principle.toLowerCase()}.`,
    youAnswered: (topic: string) => `On ${topic}, you answered`,
    aDifference: 'One difference you might point to:',
    competing: (context: string, against: string) => `in ${context}, the competing interest is ${against}`,
    question: 'What explains the difference for you?',
    reasons: {
      harm_to_others: 'Harm to other people is different from risk to yourself',
      consent: 'Consent makes the difference',
      stakes: 'The stakes are different',
      other_principle: 'Another value outweighs it in one case',
      other: 'Something else',
    },
    otherPlaceholder: 'In your own words (optional)',
    save: 'Save',
    revise: "I'd change one of these answers",
    reviseWhich: 'Which answer would you change?',
    acknowledge: "Fair point. I'll leave both as they are",
    notNow: 'Not now',
    thanks: 'Noted. This stays between you and your device.',
  },

  results: {
    title: 'Your results',
    empty: 'Answer a few topics and your results will appear here.',
    emptyCta: 'Choose a topic',
    political: 'Political spectrums',
    values: 'Values',
    thinking: 'How you think',
    worldview: 'Worldview',
    personality: 'Personality',
    personalityNote: 'Validated short form (Mini-IPIP). Your raw position on each scale, not a comparison with other people.',
    principles: 'Principles you lean on',
    principlesNote: 'How strongly your answers endorse each principle, most endorsed first. Tap one to see it topic by topic.',
    topics: 'Your positions',
    tensions: 'Where your answers pull apart',
    tensionsEmpty: 'No tensions found between your answers so far.',
    taste: 'Taste',
    interests: 'What you enjoy',
    notEnough: 'Not enough answers yet.',
    noTopicsYet: 'No topics measure this yet. They are on the way.',
    feedBy: 'Answer:',
    mixed: 'Mixed: your answers pull both ways',
    confidence: (c: number) => `Confidence ${Math.round(c * 100)}%`,
    consistency: (c: number) => `Consistency ${Math.round(c * 100)}%`,
    challengesSummary: (asked: number, held: number, distinguished: number, moved: number) =>
      [`${asked} challenge${asked === 1 ? '' : 's'}`, held && `held ${held}`, distinguished && `named a difference ${distinguished}`, moved && `reconsidered ${moved}`]
        .filter(Boolean)
        .join(' · '),
    movedLine: (source: string, steps: number, toward: string) =>
      `“${source}” moved you ${Math.abs(steps)} step${Math.abs(steps) === 1 ? '' : 's'} toward “${toward}”.`,
    status: {
      distinguished: 'You named a difference',
      revised: 'You revised an answer',
      acknowledged: 'You acknowledged it',
    },
    details: 'Details',
    selfReport: 'These results reflect what you told the app. They are a mirror, not a diagnosis.',
    basedOn: (n: number, total: number) => `Based on ${n} of ${total} topics so far.`,
    overview: 'At a glance',
    politicalMap: 'Your political map',
    mapNeeds: 'Answer topics in Economics and in Rights & liberties to see your political map.',
    clearest: 'Clearest leanings',
    leanMost: 'Principles you lean on most',
    pullApart: (n: number) => `${n} place${n === 1 ? '' : 's'} where your answers pull apart`,
    challengesTitle: 'How you handled challenges',
    challengesTotal: (n: number) => `${n} challenge${n === 1 ? '' : 's'} so far`,
    challengeParts: { held: 'Held your view', distinguished: 'Named a difference', moved: 'Reconsidered' },
    lowConfidence: 'Based on few answers so far',
    comingSoon: 'No topics yet',
    notYet: 'Not enough answers',
    rejects: 'Rejects',
    endorses: 'Endorses',
    byTopic: 'Topic by topic',
    tensionsCount: (rows: number, groups: number) =>
      `${rows} pair${rows === 1 ? '' : 's'} of answers across ${groups} principle${groups === 1 ? '' : 's'}. Most pressing first.`,
    showAll: (n: number) => `Show all ${n} principles`,
    showFewer: 'Show fewer',
    topicCount: (n: number) => `${n} topic${n === 1 ? '' : 's'}`,
    reconsideredCount: (n: number) => `reconsidered ${n}`,
    principleTensions: (n: number) => `${n} open tension${n === 1 ? '' : 's'}`,
  },

  topicResults: {
    yourAnswers: 'Your answers',
    change: 'Change',
    skipped: 'Skipped',
    unsure: 'Not sure',
    declined: 'Prefer not to say',
    notAnswered: 'Not answered',
    continue: 'Continue this topic',
  },

  settings: {
    title: 'Settings',
    backupTitle: 'Backup',
    backupExplain:
      "Your answers exist only on this device. Clearing your browser's data or uninstalling the app deletes them, so keep a backup.",
    lastBackup: (when: string | null) => (when ? `Last backup: ${when}` : 'No backup yet'),
    download: 'Save backup file',
    share: 'Share backup…',
    restore: 'Restore from backup…',
    restoreTitle: 'Restore from backup',
    restoreSummary: (n: number, date: string) => `This backup has ${n} answer${n === 1 ? '' : 's'}, saved ${date}.`,
    merge: 'Merge with my answers',
    replace: 'Replace my answers',
    cancel: 'Cancel',
    restored: 'Backup restored.',
    backupErrors: {
      'not-json': "That file isn't a backup.",
      'not-backup': "That file isn't a Who Am I backup.",
      'newer-version': 'That backup is from a newer version of the app. Update the app, then try again.',
      invalid: 'That backup is damaged and could not be read.',
    },
    questionsTitle: 'Questions',
    alwaysDeep: 'Always ask deep-dive questions',
    alwaysDeepNote: "Normally they're skipped for topics you say matter little to you.",
    storageTitle: 'Storage',
    persisted: 'Protected: the browser has agreed not to clear your answers to free up space.',
    notPersisted: 'Not protected: the browser may clear your answers if the device runs low on space.',
    persist: 'Protect my answers',
    deleteTitle: 'Delete everything',
    deleteExplain: 'Erase every answer and setting from this device. This cannot be undone.',
    deleteButton: 'Delete all my data',
    deleteConfirm: 'Delete all your answers? This cannot be undone.',
    deleted: 'All data deleted.',
    aboutLink: 'About, methods & privacy',
    contentLink: 'Content preview (every question)',
    version: (app: string, content: string) => `App ${app} · content ${content}`,
  },

  backupNudge: {
    text: 'Your answers only live on this device. Save a backup?',
    save: 'Save backup',
    later: 'Later',
  },

  storageWarning: "Your browser isn't letting this app save. Answers will be lost when you close the page.",
  contentWarning: "Some questions didn't load, so some of your answers may be missing from your results. Reload the app to try again.",

  loading: { text: 'Loading…', failed: "This part of the app didn't load. Check your connection and try again.", retry: 'Reload' },

  update: { available: 'A new version is ready.', reload: 'Update', dismiss: 'Later', offline: 'Ready to work offline.' },

  roles: {
    stance: 'Your view',
    circumstance: 'Circumstance',
    anchor: 'Principle',
    challenge: 'A challenge',
    importance: 'Importance',
  },

  evidence: {
    validated: { label: 'Validated', explain: 'A published, validated questionnaire, used word for word.' },
    adapted: { label: 'Research-based', explain: 'Adapted from published research.' },
    custom: { label: 'Original', explain: 'Questions written for this app. Not a validated instrument.' },
    'for-fun': { label: 'For fun', explain: 'Just for fun. No measurement claims.' },
  } satisfies Record<Evidence, { label: string; explain: string }>,
};
